# Crimes India : Phase 1 Data Collection

The first phase of the project is to collect data apart from the given data that can be used in our project

The data has been collected include:
1. Area of each state
2. Population in 2001 and 2011
3. Literacy rate 2001 and 2011
4. Poverty : percentage of people below poverty line
5. Unemployment: percentage of unemployed people

Though the project asked for only Area, Population and Literacy , Povery and Unemployment can also be factors affecting the crime in India

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
data_collected = pd.read_excel("C:\\Users\pooja\OneDrive\Desktop\Capstone\Data Collection_Crime India.xlsx")
data_collected

,STATE/UT,Litrecy2001,Litrecy2011,Population2001,Population2011,UnempRural 2004,UnempUrban2004,UnempRural2010,UnempUrban2010,Poverty2004,Poverty2011,PovertyDecrease,Area (km2)
0,A & N islands,81.30,86.63,356000,380000,6.2,8.8,8.0,8.4,NaN,NaN,NaN,8249
1,Andhra Pradesh,60.47,67.02,76210000,84666000,0.7,3.6,1.2,3.1,29.9,9.2,20.7,162975
2,Arunachal Pradesh,54.34,65.38,1098000,1383000,0.9,1.2,1.3,3.4,31.1,34.7,-3.6,83743
3,Assam,63.25,72.19,26656000,31169000,2.6,7.2,3.9,5.2,34.4,32.0,2.4,78438
4,Bihar,47.00,61.80,82999000,103805000,1.5,6.4,2.0,7.3,54.4,33.7,20.7,94163
5,Chandigarh,81.94,86.05,901000,1055000,2.6,4.0,24.7,3.4,NaN,NaN,NaN,114
6,Chhattisgarh,64.66,70.28,20834000,25540000,0.6,3.5,0.6,2.9,49.4,39.9,9.5,135192
7,D & N Haveli,57.63,76.24,220000,343000,3.3,3.0,4.8,5.3,NaN,NaN,NaN,603
8,Daman & Diu,78.18,87.10,158000,243000,0.3,3.0,4.0,2.4,NaN,NaN,NaN,603
9,Delhi,81.67,86.21,13851000,16753000,1.9,4.8,1.7,2.6,13.1,9.9,3.2,1484
10,Goa,82.01,88.70,1348000,1458000,11.1,8.7,4.7,4.1,25.0,5.1,19.9,3702
11,Gujarat,69.14,78.03,50671000,60384000,0.5,2.4,0.8,1.8,31.8,16.6,15.2,196024
12,Haryana,67.91,75.55,21145000,25353000,2.2,4.0,1.8,2.5,24.1,11.2,12.9,44212
13,Himachal Pradesh,76.48,82.80,6078000,6857000,1.8,3.8,1.6,4.9,22.9,8.1,14.8,55673
14,Jammu and Kashmir,55.52,67.16,10144000,12549000,1.5,4.9,2.5,6.0,13.2,10.4,2.8,42241
15,Jharkhand,53.56,66.41,26946000,32966000,1.4,6.5,3.9,6.3,45.3,37.0,8.3,79716
16,Karnataka,66.06,75.36,52851000,61131000,0.7,2.8,0.5,2.7,33.4,20.9,12.5,191791
17,Kerala,90.86,94.00,31841000,33388000,10.7,15.6,7.5,7.3,19.7,7.1,12.6,38863
18,Lakshadweep,86.66,91.85,61000,64429,7.5,25.0,9.7,5.7,NaN,NaN,NaN,32
19,Madhya Pradesh,63.74,69.32,60348000,72598000,0.5,2.8,0.7,2.9,48.6,31.7,16.9,308252
20,Maharashtra,76.84,82.34,96879000,112373000,1.0,3.6,0.6,3.2,38.1,17.4,20.7,307713
21,Manipur,70.50,76.94,2294000,2722000,1.1,5.5,3.8,4.8,38.0,36.9,1.1,22327
22,Meghalya,62.56,74.43,2319000,2964000,0.3,3.5,0.4,5.1,16.1,11.9,4.2,22429
23,Mizoram,88.80,91.33,889000,1091000,0.3,1.9,1.3,2.8,15.3,20.4,-5.1,21081
24,Nagaland,66.59,79.55,1990000,1981000,1.8,5.5,10.6,9.2,9.0,18.9,-9.9,16579
25,Odisha,63.08,72.87,36805000,41947000,5.0,13.4,3.0,4.2,57.2,32.6,24.6,155707
26,Puducherry,81.24,85.85,974000,1244000,7.0,8.1,3.0,3.1,14.1,9.7,4.4,479
27,Punjab,69.65,75.84,24359000,27704000,3.8,5.0,2.6,4.8,20.9,8.3,12.6,50362
28,Rajasthan,60.41,66.11,56507000,68621000,0.7,2.9,0.4,2.2,34.4,14.7,19.7,342239
29,Sikkim,68.81,81.42,541000,608000,2.4,3.7,4.3,0.0,31.1,8.2,22.9,7096
30,Tamil Nadu,73.45,80.33,62405679,72138958,1.2,3.5,1.5,3.2,28.9,11.3,17.6,130058
31,Tripura,73.19,80.09,3199000,3671000,13.3,28.0,9.2,17.1,40.6,14.1,26.5,10491
32,Uttar Pradesh,56.27,67.68,166198000,199581000,0.6,3.3,1.0,2.9,40.9,29.4,11.5,240928
33,Uttarakhand,71.62,78.82,8489000,10117000,1.3,5.4,1.6,2.9,32.7,11.3,21.4,53483
34,West Bengal,68.64,76.26,80176000,91348000,2.5,6.2,1.9,4.0,34.3,20.0,14.3,88752

In [3]:
data_collected.shape

(35, 13)

The table above is the data collected, it has 35 rows and 15 columns

There is some missing data in the data 

Lets look at it

In [4]:
data_collected.isna().sum()

STATE/UT           0
Litrecy2001        0
Litrecy2011        0
Population2001     0
Population2011     0
UnempRural 2004    0
UnempUrban2004     0
UnempRural2010     0
UnempUrban2010     0
Poverty2004        5
Poverty2011        5
PovertyDecrease    5
Area (km2)         0
dtype: int64

It is observed that the missing data belongs to the Poverty and is specific to union territories

We will impute the missing values using Simple imputer

In [5]:
from sklearn.impute import SimpleImputer

In [6]:
imputer = SimpleImputer(missing_values=np.NaN)
data_collected.Poverty2004=imputer.fit_transform(data_collected['Poverty2004'].values.reshape(-1,1))[:,0]
data_collected.Poverty2011=imputer.fit_transform(data_collected['Poverty2011'].values.reshape(-1,1))[:,0]
data_collected.PovertyDecrease=imputer.fit_transform(data_collected['PovertyDecrease'].values.reshape(-1,1))[:,0]

In [7]:
data_collected

,STATE/UT,Litrecy2001,Litrecy2011,Population2001,Population2011,UnempRural 2004,UnempUrban2004,UnempRural2010,UnempUrban2010,Poverty2004,Poverty2011,PovertyDecrease,Area (km2)
0,A & N islands,81.30,86.63,356000,380000,6.2,8.8,8.0,8.4,30.93,19.086667,11.843333,8249
1,Andhra Pradesh,60.47,67.02,76210000,84666000,0.7,3.6,1.2,3.1,29.90,9.200000,20.700000,162975
2,Arunachal Pradesh,54.34,65.38,1098000,1383000,0.9,1.2,1.3,3.4,31.10,34.700000,-3.600000,83743
3,Assam,63.25,72.19,26656000,31169000,2.6,7.2,3.9,5.2,34.40,32.000000,2.400000,78438
4,Bihar,47.00,61.80,82999000,103805000,1.5,6.4,2.0,7.3,54.40,33.700000,20.700000,94163
5,Chandigarh,81.94,86.05,901000,1055000,2.6,4.0,24.7,3.4,30.93,19.086667,11.843333,114
6,Chhattisgarh,64.66,70.28,20834000,25540000,0.6,3.5,0.6,2.9,49.40,39.900000,9.500000,135192
7,D & N Haveli,57.63,76.24,220000,343000,3.3,3.0,4.8,5.3,30.93,19.086667,11.843333,603
8,Daman & Diu,78.18,87.10,158000,243000,0.3,3.0,4.0,2.4,30.93,19.086667,11.843333,603
9,Delhi,81.67,86.21,13851000,16753000,1.9,4.8,1.7,2.6,13.10,9.900000,3.200000,1484
10,Goa,82.01,88.70,1348000,1458000,11.1,8.7,4.7,4.1,25.00,5.100000,19.900000,3702
11,Gujarat,69.14,78.03,50671000,60384000,0.5,2.4,0.8,1.8,31.80,16.600000,15.200000,196024
12,Haryana,67.91,75.55,21145000,25353000,2.2,4.0,1.8,2.5,24.10,11.200000,12.900000,44212
13,Himachal Pradesh,76.48,82.80,6078000,6857000,1.8,3.8,1.6,4.9,22.90,8.100000,14.800000,55673
14,Jammu and Kashmir,55.52,67.16,10144000,12549000,1.5,4.9,2.5,6.0,13.20,10.400000,2.800000,42241
15,Jharkhand,53.56,66.41,26946000,32966000,1.4,6.5,3.9,6.3,45.30,37.000000,8.300000,79716
16,Karnataka,66.06,75.36,52851000,61131000,0.7,2.8,0.5,2.7,33.40,20.900000,12.500000,191791
17,Kerala,90.86,94.00,31841000,33388000,10.7,15.6,7.5,7.3,19.70,7.100000,12.600000,38863
18,Lakshadweep,86.66,91.85,61000,64429,7.5,25.0,9.7,5.7,30.93,19.086667,11.843333,32
19,Madhya Pradesh,63.74,69.32,60348000,72598000,0.5,2.8,0.7,2.9,48.60,31.700000,16.900000,308252
20,Maharashtra,76.84,82.34,96879000,112373000,1.0,3.6,0.6,3.2,38.10,17.400000,20.700000,307713
21,Manipur,70.50,76.94,2294000,2722000,1.1,5.5,3.8,4.8,38.00,36.900000,1.100000,22327
22,Meghalya,62.56,74.43,2319000,2964000,0.3,3.5,0.4,5.1,16.10,11.900000,4.200000,22429
23,Mizoram,88.80,91.33,889000,1091000,0.3,1.9,1.3,2.8,15.30,20.400000,-5.100000,21081
24,Nagaland,66.59,79.55,1990000,1981000,1.8,5.5,10.6,9.2,9.00,18.900000,-9.900000,16579
25,Odisha,63.08,72.87,36805000,41947000,5.0,13.4,3.0,4.2,57.20,32.600000,24.600000,155707
26,Puducherry,81.24,85.85,974000,1244000,7.0,8.1,3.0,3.1,14.10,9.700000,4.400000,479
27,Punjab,69.65,75.84,24359000,27704000,3.8,5.0,2.6,4.8,20.90,8.300000,12.600000,50362
28,Rajasthan,60.41,66.11,56507000,68621000,0.7,2.9,0.4,2.2,34.40,14.700000,19.700000,342239
29,Sikkim,68.81,81.42,541000,608000,2.4,3.7,4.3,0.0,31.10,8.200000,22.900000,7096
30,Tamil Nadu,73.45,80.33,62405679,72138958,1.2,3.5,1.5,3.2,28.90,11.300000,17.600000,130058
31,Tripura,73.19,80.09,3199000,3671000,13.3,28.0,9.2,17.1,40.60,14.100000,26.500000,10491
32,Uttar Pradesh,56.27,67.68,166198000,199581000,0.6,3.3,1.0,2.9,40.90,29.400000,11.500000,240928
33,Uttarakhand,71.62,78.82,8489000,10117000,1.3,5.4,1.6,2.9,32.70,11.300000,21.400000,53483
34,West Bengal,68.64,76.26,80176000,91348000,2.5,6.2,1.9,4.0,34.30,20.000000,14.300000,88752

It is observed that the unemployment columns have % for rural unemployment and % for urban unemployment

By finding the average of rural and urban unemployment converting two columns to only one column Unemployment%

In [8]:
data_collected['Unemp%2004']=data_collected[['UnempRural 2004','UnempUrban2004']].mean(axis=1)

In [9]:
data_collected['Unemp%2010']=data_collected[['UnempRural2010','UnempUrban2010']].mean(axis=1)

In [10]:
data_collected= data_collected.drop(columns=['UnempRural 2004','UnempUrban2004','UnempRural2010','UnempUrban2010'])

In [11]:
data_collected

,STATE/UT,Litrecy2001,Litrecy2011,Population2001,Population2011,Poverty2004,Poverty2011,PovertyDecrease,Area (km2),Unemp%2004,Unemp%2010
0,A & N islands,81.30,86.63,356000,380000,30.93,19.086667,11.843333,8249,7.50,8.20
1,Andhra Pradesh,60.47,67.02,76210000,84666000,29.90,9.200000,20.700000,162975,2.15,2.15
2,Arunachal Pradesh,54.34,65.38,1098000,1383000,31.10,34.700000,-3.600000,83743,1.05,2.35
3,Assam,63.25,72.19,26656000,31169000,34.40,32.000000,2.400000,78438,4.90,4.55
4,Bihar,47.00,61.80,82999000,103805000,54.40,33.700000,20.700000,94163,3.95,4.65
5,Chandigarh,81.94,86.05,901000,1055000,30.93,19.086667,11.843333,114,3.30,14.05
6,Chhattisgarh,64.66,70.28,20834000,25540000,49.40,39.900000,9.500000,135192,2.05,1.75
7,D & N Haveli,57.63,76.24,220000,343000,30.93,19.086667,11.843333,603,3.15,5.05
8,Daman & Diu,78.18,87.10,158000,243000,30.93,19.086667,11.843333,603,1.65,3.20
9,Delhi,81.67,86.21,13851000,16753000,13.10,9.900000,3.200000,1484,3.35,2.15
10,Goa,82.01,88.70,1348000,1458000,25.00,5.100000,19.900000,3702,9.90,4.40
11,Gujarat,69.14,78.03,50671000,60384000,31.80,16.600000,15.200000,196024,1.45,1.30
12,Haryana,67.91,75.55,21145000,25353000,24.10,11.200000,12.900000,44212,3.10,2.15
13,Himachal Pradesh,76.48,82.80,6078000,6857000,22.90,8.100000,14.800000,55673,2.80,3.25
14,Jammu and Kashmir,55.52,67.16,10144000,12549000,13.20,10.400000,2.800000,42241,3.20,4.25
15,Jharkhand,53.56,66.41,26946000,32966000,45.30,37.000000,8.300000,79716,3.95,5.10
16,Karnataka,66.06,75.36,52851000,61131000,33.40,20.900000,12.500000,191791,1.75,1.60
17,Kerala,90.86,94.00,31841000,33388000,19.70,7.100000,12.600000,38863,13.15,7.40
18,Lakshadweep,86.66,91.85,61000,64429,30.93,19.086667,11.843333,32,16.25,7.70
19,Madhya Pradesh,63.74,69.32,60348000,72598000,48.60,31.700000,16.900000,308252,1.65,1.80
20,Maharashtra,76.84,82.34,96879000,112373000,38.10,17.400000,20.700000,307713,2.30,1.90
21,Manipur,70.50,76.94,2294000,2722000,38.00,36.900000,1.100000,22327,3.30,4.30
22,Meghalya,62.56,74.43,2319000,2964000,16.10,11.900000,4.200000,22429,1.90,2.75
23,Mizoram,88.80,91.33,889000,1091000,15.30,20.400000,-5.100000,21081,1.10,2.05
24,Nagaland,66.59,79.55,1990000,1981000,9.00,18.900000,-9.900000,16579,3.65,9.90
25,Odisha,63.08,72.87,36805000,41947000,57.20,32.600000,24.600000,155707,9.20,3.60
26,Puducherry,81.24,85.85,974000,1244000,14.10,9.700000,4.400000,479,7.55,3.05
27,Punjab,69.65,75.84,24359000,27704000,20.90,8.300000,12.600000,50362,4.40,3.70
28,Rajasthan,60.41,66.11,56507000,68621000,34.40,14.700000,19.700000,342239,1.80,1.30
29,Sikkim,68.81,81.42,541000,608000,31.10,8.200000,22.900000,7096,3.05,2.15
30,Tamil Nadu,73.45,80.33,62405679,72138958,28.90,11.300000,17.600000,130058,2.35,2.35
31,Tripura,73.19,80.09,3199000,3671000,40.60,14.100000,26.500000,10491,20.65,13.15
32,Uttar Pradesh,56.27,67.68,166198000,199581000,40.90,29.400000,11.500000,240928,1.95,1.95
33,Uttarakhand,71.62,78.82,8489000,10117000,32.70,11.300000,21.400000,53483,3.35,2.25
34,West Bengal,68.64,76.26,80176000,91348000,34.30,20.000000,14.300000,88752,4.35,2.95

In [12]:
data_collected.to_csv('data_collected.csv',index=False)

The above data has been cleaned imputed and  now can be used for futhur analysis

## Data Source:
States and area: https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_area

Literacy rate: https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_literacy_rate

Population: https://datasource.kapsarc.org/explore/dataset/statewise-census-data-in-india-1901-2011

Unemployment reat:https://www.pib.gov.in/newsite/PrintRelease.aspx?relid=124224

Poverty: https://prsindia.org/theprsblog/more-privatisation-on-the-cards